name: "Licenta"

x-build-base: &build_base
    context: .
    dockerfile: storage_server/dockerfile

x-server_base: &default_storage_server
  build: *build_base

  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - NET_RAW
  
  tty: true
  privileged: true

services:
  #### HEAD SERVER ####
  head_server:
    container_name: head_server
    build:
      context: .
      dockerfile: ./head_server/dockerfile
    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true
    privileged: true

    # command: bash -c "sleep infinity"

    networks:
      net:
        ipv4_address: "192.168.1.100"
    
    volumes:
      - ./head_server/scripts:/project/scripts
      - ./lib:/project/lib

  #### METADATA SERVER ####
  metadata_server:
    container_name: metadata_server

    build:
      context: .
      dockerfile: ./metadata_server/dockerfile
    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    command: bash -c "sleep infinity"

    networks:
      net:
        ipv4_address: "192.168.1.101"

    volumes:
      - ./metadata_server/scripts:/project/scripts
      - ./lib:/project/lib
  
  #### STORAGE SERVERS ####

  ### SERVER 1 ####
  server1:
    <<: *default_storage_server
    container_name: storage_server1
    
    build:
      <<: *build_base
      args:
        USERNAME: storage_s1
    
    networks:
      net:
        ipv4_address: "192.168.1.201"

  ### SERVER 2 ####
  server2:
    <<: *default_storage_server
    container_name: storage_server2

    build:
      <<: *build_base
      args:
        USERNAME: storage_s2

    networks:
      net:
        ipv4_address: "192.168.1.202"

  #### SERVER 3 ####
  server3:
    <<: *default_storage_server
    container_name: storage_server3
    
    build:
      <<: *build_base
      args:
        USERNAME: storage_s3
    
    networks:
      net:
        ipv4_address: "192.168.1.203"
  
#### NETWORKS ####
networks:
  net: 
    driver_opts: 
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
  
  