name: "Licenta"

services:
  #### HEAD SERVER ####
  head_server:
    container_name: head_server
    build:
      context: .
      dockerfile: head_server/dockerfile
    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    networks:
      net:
        ipv4_address: "192.168.1.100"
    
    # command: bash -c "/scripts/setup.sh && sleep infinity"

  #### METADATA SERVER ####
  metadata_server:
    container_name: metadata_server

    build:
      context: .
      dockerfile: metadata_server/dockerfile
    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    networks:
      net:
        ipv4_address: "192.168.1.101"

    # command: bash -c "/scripts/setup.sh && sleep infinity"
  
  #### STORAGE SERVERS ####

  #### SERVER 1 ####
  server1:
    container_name: server1

    build:
      context: .
      dockerfile: storage_server/dockerfile
    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    networks:
      net:
        ipv4_address: "192.168.1.201"
    
    # command: bash -c "/scripts/setup.sh && sleep infinity"

  #### SERVER 2 ####
  server2:
    container_name: server2
    
    build:
      context: .
      dockerfile: storage_server/dockerfile

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    networks:
      net:
        ipv4_address: "192.168.1.202"

    # command: bash -c "/scripts/setup.sh && sleep infinity"
  
  #### SERVER 3 ####
  server3:
    container_name: server3
    
    build:
      context: .
      dockerfile: storage_server/dockerfile

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    
    tty: true

    networks:
      net:
        ipv4_address: "192.168.1.203"

    # command: bash -c "/scripts/setup.sh && sleep infinity"
    
#### NETWORKS ####
networks:
  net: 
    driver_opts: 
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
  
  