FROM ubuntu:latest

RUN mkdir -p /project/lib
RUN mkdir -p /project/scripts
RUN mkdir -p /project/mpi

COPY ./lib /project/lib
COPY ./metadata_server/scripts /project/scripts
COPY ./mpi /project/mpi

# installing everything
RUN apt update && apt install -y \
    build-essential net-tools iputils-ping git wget vim \
    memcached libmemcached-tools libmemcached-dev libfmt-dev \
    libprotobuf-dev protobuf-compiler libspdlog-dev \
    openssh-client openssh-server

ARG USERNAME=meta_s
ARG USER_UID=1001
ARG USER_GID=$USER_UID

WORKDIR /etc/sudoers.d

# Create user and group
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m -s /bin/bash $USERNAME \
    # Add sudo support (optional)
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Set the working directory to user's home
WORKDIR /home/$USERNAME
RUN mkdir -p /home/$USERNAME/.ssh && chmod 700 /home/$USERNAME/.ssh
RUN cp /project/mpi/ssh_config /home/$USERNAME/.ssh/config

# SSH keys
RUN cp /project/mpi/id_rsa /home/$USERNAME/.ssh
RUN cp /project/mpi/id_rsa.pub /home/$USERNAME/.ssh
RUN chown $USERNAME:$USERNAME /home/$USERNAME/.ssh/id_rsa
RUN chmod 600 /home/$USERNAME/.ssh/id_rsa
RUN cat /home/$USERNAME/.ssh/id_rsa.pub >> /home/$USERNAME/.ssh/authorized_keys && \
    chmod 600 /home/$USERNAME/.ssh/authorized_keys
RUN mkdir /var/run/sshd
EXPOSE 22

# ensuring the protofiles are well-generated
WORKDIR /project/lib
RUN rm metadata.pb*
RUN protoc --cpp_out=. metadata.proto
RUN mv metadata.pb.cc metadata.pb.cpp

# installing ASIO and CLI11
RUN mkdir /stuff
WORKDIR /stuff
RUN git clone https://github.com/chriskohlhoff/asio.git
RUN cp -r asio/asio/include/asio /usr/local/include/
RUN cp asio/asio/include/asio.hpp /usr/local/include/
RUN wget https://github.com/CLIUtils/CLI11/releases/download/v2.5.0/CLI11.hpp
RUN cp CLI11.hpp /usr/local/include/

# compiling the project
# WORKDIR /project/scripts
# RUN make SRC=test_server.cpp

RUN chown -R $USERNAME:$USERNAME /home/$USERNAME
RUN chown -R $USERNAME:$USERNAME /project
WORKDIR /project/scripts